// Single-file HTML report — inlined CSS + screenshots as data URIs so it can be
// attached anywhere (CI artifact, email, ticket) and opened with no server.
// (documentation/06-reporting.md)

import { readFile } from "node:fs/promises";
import type { JudgeVerdict, PageResult, RunResult, Signals } from "../types.js";
import { pathOf, hostOf, fmtDuration, statusOrder, coverageLine } from "./index.js";

const STATUS_LABEL: Record<PageResult["status"], string> = {
  fail: "FAIL",
  warn: "WARN",
  pass: "PASS",
  skipped: "SKIP",
};

export async function renderHtml(result: RunResult): Promise<string> {
  const pages = [...result.pages].sort((a, b) => statusOrder(a) - statusOrder(b) || a.url.localeCompare(b.url));
  const filters = filterBar(pages);
  const timing = timingSection(pages);

  // One row per page, each expanding in place to its own evidence — the table
  // and the detail blocks used to be separate sections, which meant every
  // finding was printed twice and reading the evidence for a red meant
  // following an anchor away from the list you were scanning.
  const rows: string[] = [];
  for (const p of pages) rows.push(await pageRowHtml(p));

  const judgedCount = result.pages.filter((p) => p.decidedBy === "judge").length;
  const unjudgedCount = result.pages.filter((p) => p.unjudged || p.decidedBy === "budget" || p.decidedBy === "error").length;

  const meta = [
    ["Target", esc(result.target.url)],
    ["Verdict", result.verdict],
    result.target.deployRef ? ["Deploy", esc(result.target.deployRef)] : null,
    ["Duration", fmtDuration(result.durationMs)],
    ["Pages", String(result.pages.length)],
    ["Model spend", `$${result.cost.modelUsd.toFixed(2)}`],
    ["Judged / unjudged", `Judged ${judgedCount} · unjudged ${unjudgedCount}`],
    result.budgetsExhausted.length ? ["Budgets exhausted", esc(result.budgetsExhausted.join(", "))] : null,
    ["Run ID", esc(result.runId)],
  ]
    .filter((x): x is [string, string] => x !== null)
    .map(([k, v]) => `<div class="meta-item"><span>${k}</span><b>${v}</b></div>`)
    .join("");

  const c = result.counts;
  const summary =
    `${c.fail} failed · ${c.pass} passed · ${c.warn} warned` + (c.skipped ? ` · ${c.skipped} skipped` : "");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>vigil · ${result.verdict} · ${hostOf(result.target.url)}</title>
<style>${CSS}</style>
</head>
<body>
<header class="banner v-${result.verdict}">
  <div class="verdict">${result.verdict}</div>
  <div class="sub">${esc(hostOf(result.target.url))} — ${summary}</div>
</header>
<section class="meta">${meta}</section>
<section class="coverage"><b>Coverage</b> — ${esc(coverageLine(result.coverage))}</section>
${timing}
<section>
  <h2>Pages</h2>
  ${filters}
  <div class="row-head"><span>Status</span><span>Page</span><span>Finding</span><span>Source</span></div>
  <div class="page-list">${rows.join("\n")}</div>
  <p class="empty-note" hidden>No pages with that status.</p>
</section>
<footer>Generated by vigil · stateless post-deploy sanity check · ${esc(result.startedAt)}</footer>
<script>${FILTER_JS}</script>
</body>
</html>`;
}

/** Clickable status filter — counts come from the pages actually in the run. */
function filterBar(pages: PageResult[]): string {
  const order: PageResult["status"][] = ["fail", "warn", "pass", "skipped"];
  const buttons = [`<button class="f-btn active" data-filter="all">All <b>${pages.length}</b></button>`];
  for (const s of order) {
    const n = pages.filter((p) => p.status === s).length;
    if (n === 0) continue; // a filter that can only ever show nothing is noise
    buttons.push(`<button class="f-btn" data-filter="${s}"><span class="dot d-${s}"></span>${STATUS_LABEL[s]} <b>${n}</b></button>`);
  }
  return `<div class="filters">${buttons.join("")}</div>`;
}

// Settle time is the single best predictor of whether a capture caught the
// real page: dogfooding showed a hard split where pages settling fast held
// full content and pages settling slow were still booting (doc 04). Bucketing
// it makes a target's overall responsiveness legible at a glance, and makes a
// creeping regression across a deploy obvious without diffing raw numbers.
const TIMING_BUCKETS: { label: string; hint: string; cls: string; test: (ms: number) => boolean }[] = [
  { label: "Fast", hint: "under 2s", cls: "t-fast", test: (ms) => ms < 2000 },
  { label: "Moderate", hint: "2–5s", cls: "t-mod", test: (ms) => ms >= 2000 && ms <= 5000 },
  { label: "Slow", hint: "over 5s", cls: "t-slow", test: (ms) => ms > 5000 },
];

function timingSection(pages: PageResult[]): string {
  if (pages.length === 0) return "";
  const timed = pages.filter((p) => p.signals.document.settledMs != null);
  // Note: not an early return when `timed` is empty — a run where every page
  // failed to navigate still needs to say so, rather than silently dropping
  // the whole section and looking like timing was never measured.

  const cards = TIMING_BUCKETS.map((b) => {
    const inBucket = timed
      .filter((p) => b.test(p.signals.document.settledMs!))
      .sort((a, z) => z.signals.document.settledMs! - a.signals.document.settledMs!);
    const items = inBucket.length
      ? `<ul>${inBucket
          .map(
            (p) =>
              `<li><span class="dot d-${p.status}"></span><span class="t-url">${esc(pathOf(p.url))}</span>` +
              `<span class="t-ms">${p.signals.document.settledMs}ms</span></li>`
          )
          .join("")}</ul>`
      : `<p class="t-none">none</p>`;
    return `<div class="t-card ${b.cls}">
      <div class="t-head"><b>${b.label}</b> <span>${b.hint}</span><span class="t-count">${inBucket.length}</span></div>
      ${items}
    </div>`;
  }).join("");

  const untimed = pages.length - timed.length;
  const note = untimed ? `<p class="t-note">${untimed} page(s) never produced a document — no settle time recorded.</p>` : "";
  return `<section>
  <h2>Settle timing</h2>
  <div class="timing">${cards}</div>
  ${note}
</section>`;
}

/**
 * One page = one expandable row: the scannable summary line and the evidence
 * behind it live in the same element, so nothing is printed twice and reading
 * a red never navigates away from the list.
 *
 * Screenshots are embedded for non-pass pages only. They dominate the file
 * size (base64 data URIs), and a green page's screenshot is the one nobody
 * opens — passes still expand, just to their signals rather than an image.
 */
async function pageRowHtml(p: PageResult): Promise<string> {
  const id = anchorId(p);
  const open = p.status === "fail" ? " open" : "";
  const rule = p.hardRule ? ` ${p.hardRule}` : "";

  let shots = "";
  if (p.status !== "pass") {
    const shot = await imgTag(p.signals.screenshotPath, "capture");
    const retryShot = p.retrySignals ? await imgTag(p.retrySignals.screenshotPath, "retry capture") : "";
    if (shot || retryShot) shots = `<div class="shots">${shot}${retryShot}</div>`;
  }

  return `<details id="${id}" class="page-row s-${p.status}" data-status="${p.status}"${open}>
  <summary>
    <span class="c-status"><span class="pill p-${p.status}">${STATUS_LABEL[p.status]}${rule}</span> <span class="tag">${esc(p.decidedBy)}</span></span>
    <span class="c-url">${esc(pathOf(p.url))}</span>
    <span class="c-find">${esc(p.headline)}</span>
    <span class="c-src">${p.source}</span>
  </summary>
  <div class="detail-body">
    ${p.flaky ? `<p class="note">Passed on retry — recorded as flaky.</p>` : ""}
    ${unjudgedNote(p)}
    ${judgeCard(p.judge)}
    ${shots}
    ${fidelityEvidence(p.fidelityWarnings)}
    ${signalEvidence(p.signals)}
  </div>
</details>`;
}

function unjudgedNote(p: PageResult): string {
  if (!p.unjudged) return "";
  const msg =
    p.decidedBy === "error"
      ? `Unjudged — judge error${p.judgeError ? `: ${p.judgeError}` : ""}`
      : "Unjudged — model budget exhausted";
  return `<p class="note">${esc(msg)}</p>`;
}

function judgeCard(j: JudgeVerdict | undefined): string {
  if (!j) return "";
  const barColor = j.status === "fail" ? "var(--red)" : j.status === "warn" ? "var(--yellow)" : "var(--green)";
  const pct = Math.round(j.confidence * 100);

  const reasonsList = j.reasons.length
    ? `<ul class="judge-reasons">${j.reasons
        .map(
          (r) =>
            `<li><span class="tag">${esc(r.kind)}</span> <b>${esc(r.summary)}</b>${
              r.evidence ? `<div class="evi-code">${esc(r.evidence)}</div>` : ""
            }</li>`
        )
        .join("")}</ul>`
    : "";

  return `<div class="evi judge-card">
    <h4>Judge verdict</h4>
    <div class="judge-header">
      <span class="pill p-${j.status}">${STATUS_LABEL[j.status] ?? j.status.toUpperCase()}</span>
      <span>Confidence ${j.confidence.toFixed(2)}</span>
      <div class="meter-bar"><div class="meter-fill" style="width:${pct}%;background:${barColor}"></div></div>
    </div>
    ${reasonsList}
  </div>`;
}

function fidelityEvidence(warnings: string[] | undefined): string {
  if (!warnings || warnings.length === 0) return "";
  const items = warnings.map((w) => `<li>${esc(w)}</li>`).join("");
  return `<div class="evi"><h4>Data fidelity</h4><ul>${items}</ul></div>`;
}

function signalEvidence(s: Signals): string {
  const blocks: string[] = [];

  const badReq = s.requests.filter((r) => r.status === null || (r.status ?? 0) >= 400);
  if (badReq.length) {
    const items = badReq
      .slice(0, 15)
      .map(
        (r) =>
          `<li>${r.firstParty ? "" : `<span class="tag">3rd-party</span> `}${esc(r.method)} ${esc(pathOf(r.url))} → ${r.status ?? esc(r.failure ?? "failed")}</li>`
      )
      .join("");
    blocks.push(`<div class="evi"><h4>Failed requests (${badReq.length})</h4><ul>${items}</ul></div>`);
  }

  if (s.console.length) {
    const items = s.console
      .slice(0, 10)
      .map((c) => `<li>${esc(c.text)}${c.count > 1 ? ` <span class="tag">×${c.count}</span>` : ""}</li>`)
      .join("");
    blocks.push(`<div class="evi"><h4>Console errors</h4><ul>${items}</ul></div>`);
  }

  if (s.pageErrors.length) {
    const items = s.pageErrors.slice(0, 5).map((e) => `<li>${esc(e)}</li>`).join("");
    blocks.push(`<div class="evi"><h4>Uncaught exceptions</h4><ul>${items}</ul></div>`);
  }

  const facts: string[] = [
    `document ${s.document.status ?? esc(s.document.navigationError ?? "no response")}`,
    `${s.render.textLength} chars rendered`,
    s.render.title ? `title “${esc(s.render.title)}”` : "",
    s.render.spinnerStuck ? "spinner stuck" : "",
    s.render.errorMarkersFound.length ? `error markers: ${s.render.errorMarkersFound.map(esc).join(", ")}` : "",
    s.timedOut ? "visit timed out" : "",
    s.document.settledMs != null ? `settled in ${s.document.settledMs}ms` : "",
  ].filter(Boolean);
  blocks.push(`<div class="evi"><h4>Render & timing</h4><p>${facts.join(" · ")}</p></div>`);

  return blocks.join("\n");
}

async function imgTag(path: string, alt: string): Promise<string> {
  if (!path) return "";
  try {
    const buf = await readFile(path);
    const b64 = buf.toString("base64");
    return `<figure><img alt="${esc(alt)}" src="data:image/png;base64,${b64}"><figcaption>${esc(alt)}</figcaption></figure>`;
  } catch {
    return "";
  }
}

function anchorId(p: PageResult): string {
  return "pg-" + p.url.replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

function esc(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
}

// Inline, dependency-free, and inert if scripting is off — the table still
// renders every page, the filter just stops being interactive. Kept as a
// plain string (no template interpolation) so nothing in it can collide with
// the surrounding template literal.
const FILTER_JS = `
(function () {
  var btns = document.querySelectorAll('.f-btn');
  var rows = document.querySelectorAll('.page-row[data-status]');
  var empty = document.querySelector('.empty-note');
  function apply(f) {
    var shown = 0;
    rows.forEach(function (r) {
      var on = f === 'all' || r.getAttribute('data-status') === f;
      r.hidden = !on;
      if (on) shown++;
    });
    if (empty) empty.hidden = shown !== 0;
  }
  btns.forEach(function (b) {
    b.addEventListener('click', function () {
      btns.forEach(function (x) { x.classList.toggle('active', x === b); });
      apply(b.getAttribute('data-filter'));
    });
  });
})();
`;

const CSS = `
:root{--bg:#fff;--fg:#1a1a1a;--muted:#666;--line:#e2e2e2;--card:#f7f7f8;
--green:#1a7f37;--yellow:#9a6700;--red:#cf222e;--gray:#57606a;}
@media(prefers-color-scheme:dark){:root{--bg:#0d1117;--fg:#e6edf3;--muted:#8b949e;--line:#30363d;--card:#161b22;
--green:#3fb950;--yellow:#d29922;--red:#f85149;--gray:#8b949e;}}
*{box-sizing:border-box}body{margin:0;font:15px/1.5 system-ui,-apple-system,Segoe UI,Roboto,sans-serif;background:var(--bg);color:var(--fg);padding:0 0 4rem}
.banner{padding:1.5rem 2rem;color:#fff}.banner .verdict{font-size:1.8rem;font-weight:800;letter-spacing:.02em}
.banner .sub{opacity:.95;margin-top:.25rem}
.v-HEALTHY{background:var(--green)}.v-DEGRADED{background:var(--yellow)}.v-BROKEN{background:var(--red)}.v-INCONCLUSIVE{background:var(--gray)}
.meta{display:flex;flex-wrap:wrap;gap:1.25rem;padding:1rem 2rem;border-bottom:1px solid var(--line)}
.meta-item span{display:block;color:var(--muted);font-size:.72rem;text-transform:uppercase;letter-spacing:.04em}
.meta-item b{font-size:.95rem}
.coverage{padding:.6rem 2rem;border-bottom:1px solid var(--line);font-size:.82rem;color:var(--muted)}
.coverage b{color:var(--fg)}
section{padding:1.25rem 2rem}h2{font-size:1.1rem;margin:.5rem 0 1rem}h4{margin:.75rem 0 .35rem;font-size:.82rem;color:var(--muted);text-transform:uppercase;letter-spacing:.03em}
a{color:inherit}
/* Page list — one expandable row per page, laid out on a shared grid so the
   collapsed rows still read like a table. */
.row-head{display:grid;gap:.6rem;padding:.4rem .7rem;border-bottom:1px solid var(--line);
grid-template-columns:minmax(140px,auto) minmax(140px,1.2fr) minmax(180px,2fr) 80px}
.row-head span{color:var(--muted);font-weight:600;font-size:.72rem;text-transform:uppercase;letter-spacing:.03em}
.page-row{border-bottom:1px solid var(--line)}
.page-row>summary{display:grid;gap:.6rem;align-items:start;padding:.5rem .7rem;cursor:pointer;font-size:.88rem;
list-style:none;grid-template-columns:minmax(140px,auto) minmax(140px,1.2fr) minmax(180px,2fr) 80px}
.page-row>summary::-webkit-details-marker{display:none}
.page-row>summary:hover{background:var(--card)}
.page-row[open]>summary{background:var(--card)}
.c-url{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;word-break:break-all}
.c-src{color:var(--muted);font-size:.8rem}
.c-status{white-space:nowrap}
@media(max-width:760px){
  .row-head{display:none}
  .page-row>summary{grid-template-columns:1fr;gap:.25rem}
  .c-src{font-size:.72rem}
}
.pill{display:inline-block;padding:.1rem .45rem;border-radius:4px;font-size:.7rem;font-weight:700;color:#fff;white-space:nowrap}
.p-fail{background:var(--red)}.p-warn{background:var(--yellow)}.p-pass{background:var(--green)}.p-skipped{background:var(--gray)}
.detail-body{padding:.25rem .7rem 1rem;background:var(--card)}
.shots{display:flex;flex-wrap:wrap;gap:1rem;margin:.5rem 0}
figure{margin:0;max-width:520px}figure img{width:100%;border:1px solid var(--line);border-radius:6px;display:block}
figcaption{color:var(--muted);font-size:.75rem;margin-top:.25rem}
.evi ul{margin:.25rem 0;padding-left:1.1rem}.evi li{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.82rem;word-break:break-all}
.tag{background:var(--line);color:var(--muted);padding:0 .3rem;border-radius:3px;font-size:.7rem}
.note{color:var(--yellow);font-weight:600}
.meter-bar{display:inline-block;width:100px;height:8px;background:var(--line);border-radius:4px;overflow:hidden;vertical-align:middle;margin-left:.5rem}
.meter-fill{height:100%;border-radius:4px}
.judge-header{display:flex;align-items:center;gap:.5rem;margin-bottom:.5rem;font-size:.85rem}
.judge-reasons{margin:.25rem 0;padding-left:1.1rem;list-style:none}
.judge-reasons li{margin-bottom:.4rem;font-size:.85rem}
.evi-code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.8rem;color:var(--muted);margin-top:.15rem}
footer{padding:1.5rem 2rem;color:var(--muted);font-size:.8rem}
.filters{display:flex;flex-wrap:wrap;gap:.4rem;margin-bottom:.75rem}
.f-btn{font:inherit;font-size:.78rem;color:var(--fg);background:var(--card);border:1px solid var(--line);
border-radius:999px;padding:.25rem .7rem;cursor:pointer;display:inline-flex;align-items:center;gap:.35rem}
.f-btn:hover{border-color:var(--muted)}
.f-btn.active{background:var(--fg);color:var(--bg);border-color:var(--fg)}
.f-btn b{font-weight:700}
.dot{display:inline-block;width:7px;height:7px;border-radius:50%}
.d-fail{background:var(--red)}.d-warn{background:var(--yellow)}.d-pass{background:var(--green)}.d-skipped{background:var(--gray)}
.empty-note{color:var(--muted);font-size:.85rem;padding:.75rem 0}
.timing{display:flex;flex-wrap:wrap;gap:.75rem}
.t-card{flex:1 1 220px;min-width:220px;background:var(--card);border:1px solid var(--line);border-radius:8px;padding:.7rem .85rem}
.t-card.t-fast{border-left:3px solid var(--green)}
.t-card.t-mod{border-left:3px solid var(--yellow)}
.t-card.t-slow{border-left:3px solid var(--red)}
.t-head{display:flex;align-items:baseline;gap:.4rem;margin-bottom:.4rem;font-size:.9rem}
.t-head span{color:var(--muted);font-size:.75rem}
.t-head .t-count{margin-left:auto;font-weight:700;font-size:1rem;color:var(--fg)}
.t-card ul{margin:0;padding:0;list-style:none}
.t-card li{display:flex;align-items:center;gap:.4rem;font-size:.78rem;padding:.12rem 0}
.t-url{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.t-ms{margin-left:auto;color:var(--muted);font-variant-numeric:tabular-nums}
.t-none{color:var(--muted);font-size:.78rem;margin:0}
.t-note{color:var(--muted);font-size:.78rem;margin:.6rem 0 0}
`;
