// Single-file HTML report — inlined CSS + screenshots as data URIs so it can be
// attached anywhere (CI artifact, email, ticket) and opened with no server.
// (documentation/06-reporting.md)

import { readFile } from "node:fs/promises";
import type { PageResult, RunResult, Signals } from "../types.js";
import { pathOf, hostOf, fmtDuration, statusOrder, coverageLine } from "./index.js";

const STATUS_LABEL: Record<PageResult["status"], string> = {
  fail: "FAIL",
  warn: "WARN",
  pass: "PASS",
  skipped: "SKIP",
};

export async function renderHtml(result: RunResult): Promise<string> {
  const pages = [...result.pages].sort((a, b) => statusOrder(a) - statusOrder(b) || a.url.localeCompare(b.url));
  const rows = pages.map(rowHtml).join("\n");

  const details: string[] = [];
  for (const p of pages) {
    if (p.status === "pass") continue; // only fails/warns/skips get detail blocks
    details.push(await detailHtml(p));
  }

  const meta = [
    ["Target", esc(result.target.url)],
    ["Verdict", result.verdict],
    result.target.deployRef ? ["Deploy", esc(result.target.deployRef)] : null,
    ["Duration", fmtDuration(result.durationMs)],
    ["Pages", String(result.pages.length)],
    ["Model spend", `$${result.cost.modelUsd.toFixed(2)}`],
    result.budgetsExhausted.length ? ["Budgets exhausted", esc(result.budgetsExhausted.join(", "))] : null,
    ["Run ID", esc(result.runId)],
  ]
    .filter((x): x is [string, string] => x !== null)
    .map(([k, v]) => `<div class="meta-item"><span>${k}</span><b>${v}</b></div>`)
    .join("");

  const c = result.counts;
  const summary =
    `${c.fail} failed · ${c.pass} passed · ${c.warn} warned` + (c.skipped ? ` · ${c.skipped} skipped` : "");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>vigil · ${result.verdict} · ${hostOf(result.target.url)}</title>
<style>${CSS}</style>
</head>
<body>
<header class="banner v-${result.verdict}">
  <div class="verdict">${result.verdict}</div>
  <div class="sub">${esc(hostOf(result.target.url))} — ${summary}</div>
</header>
<section class="meta">${meta}</section>
<section class="coverage"><b>Coverage</b> — ${esc(coverageLine(result.coverage))}</section>
<section>
  <h2>Pages</h2>
  <table class="pages">
    <thead><tr><th>Status</th><th>Page</th><th>Finding</th><th>Source</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
</section>
${details.length ? `<section><h2>Details</h2>${details.join("\n")}</section>` : ""}
<footer>Generated by vigil · stateless post-deploy sanity check · ${esc(result.startedAt)}</footer>
</body>
</html>`;
}

function rowHtml(p: PageResult): string {
  const id = anchorId(p);
  const link = p.status === "pass" ? esc(pathOf(p.url)) : `<a href="#${id}">${esc(pathOf(p.url))}</a>`;
  return `<tr class="s-${p.status}">
  <td><span class="pill p-${p.status}">${STATUS_LABEL[p.status]}${p.hardRule ? ` ${p.hardRule}` : ""}</span></td>
  <td class="url">${link}</td>
  <td>${esc(p.headline)}</td>
  <td class="src">${p.source}</td>
</tr>`;
}

async function detailHtml(p: PageResult): Promise<string> {
  const id = anchorId(p);
  const shot = await imgTag(p.signals.screenshotPath, "capture");
  const retryShot = p.retrySignals ? await imgTag(p.retrySignals.screenshotPath, "retry capture") : "";
  const evidence = signalEvidence(p.signals);
  const open = p.status === "fail" ? " open" : "";
  return `<details id="${id}" class="detail d-${p.status}"${open}>
  <summary><span class="pill p-${p.status}">${STATUS_LABEL[p.status]}${p.hardRule ? ` ${p.hardRule}` : ""}</span> ${esc(pathOf(p.url))} — ${esc(p.headline)}</summary>
  <div class="detail-body">
    ${p.flaky ? `<p class="note">Passed on retry — recorded as flaky.</p>` : ""}
    <div class="shots">${shot}${retryShot}</div>
    ${fidelityEvidence(p.fidelityWarnings)}
    ${evidence}
  </div>
</details>`;
}

function fidelityEvidence(warnings: string[] | undefined): string {
  if (!warnings || warnings.length === 0) return "";
  const items = warnings.map((w) => `<li>${esc(w)}</li>`).join("");
  return `<div class="evi"><h4>Data fidelity</h4><ul>${items}</ul></div>`;
}

function signalEvidence(s: Signals): string {
  const blocks: string[] = [];

  const badReq = s.requests.filter((r) => r.status === null || (r.status ?? 0) >= 400);
  if (badReq.length) {
    const items = badReq
      .slice(0, 15)
      .map(
        (r) =>
          `<li>${r.firstParty ? "" : `<span class="tag">3rd-party</span> `}${esc(r.method)} ${esc(pathOf(r.url))} → ${r.status ?? esc(r.failure ?? "failed")}</li>`
      )
      .join("");
    blocks.push(`<div class="evi"><h4>Failed requests (${badReq.length})</h4><ul>${items}</ul></div>`);
  }

  if (s.console.length) {
    const items = s.console
      .slice(0, 10)
      .map((c) => `<li>${esc(c.text)}${c.count > 1 ? ` <span class="tag">×${c.count}</span>` : ""}</li>`)
      .join("");
    blocks.push(`<div class="evi"><h4>Console errors</h4><ul>${items}</ul></div>`);
  }

  if (s.pageErrors.length) {
    const items = s.pageErrors.slice(0, 5).map((e) => `<li>${esc(e)}</li>`).join("");
    blocks.push(`<div class="evi"><h4>Uncaught exceptions</h4><ul>${items}</ul></div>`);
  }

  const facts: string[] = [
    `document ${s.document.status ?? esc(s.document.navigationError ?? "no response")}`,
    `${s.render.textLength} chars rendered`,
    s.render.title ? `title “${esc(s.render.title)}”` : "",
    s.render.spinnerStuck ? "spinner stuck" : "",
    s.render.errorMarkersFound.length ? `error markers: ${s.render.errorMarkersFound.map(esc).join(", ")}` : "",
    s.timedOut ? "visit timed out" : "",
    s.document.settledMs != null ? `settled in ${s.document.settledMs}ms` : "",
  ].filter(Boolean);
  blocks.push(`<div class="evi"><h4>Render & timing</h4><p>${facts.join(" · ")}</p></div>`);

  return blocks.join("\n");
}

async function imgTag(path: string, alt: string): Promise<string> {
  if (!path) return "";
  try {
    const buf = await readFile(path);
    const b64 = buf.toString("base64");
    return `<figure><img alt="${esc(alt)}" src="data:image/png;base64,${b64}"><figcaption>${esc(alt)}</figcaption></figure>`;
  } catch {
    return "";
  }
}

function anchorId(p: PageResult): string {
  return "pg-" + p.url.replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

function esc(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
}

const CSS = `
:root{--bg:#fff;--fg:#1a1a1a;--muted:#666;--line:#e2e2e2;--card:#f7f7f8;
--green:#1a7f37;--yellow:#9a6700;--red:#cf222e;--gray:#57606a;}
@media(prefers-color-scheme:dark){:root{--bg:#0d1117;--fg:#e6edf3;--muted:#8b949e;--line:#30363d;--card:#161b22;
--green:#3fb950;--yellow:#d29922;--red:#f85149;--gray:#8b949e;}}
*{box-sizing:border-box}body{margin:0;font:15px/1.5 system-ui,-apple-system,Segoe UI,Roboto,sans-serif;background:var(--bg);color:var(--fg);padding:0 0 4rem}
.banner{padding:1.5rem 2rem;color:#fff}.banner .verdict{font-size:1.8rem;font-weight:800;letter-spacing:.02em}
.banner .sub{opacity:.95;margin-top:.25rem}
.v-HEALTHY{background:var(--green)}.v-DEGRADED{background:var(--yellow)}.v-BROKEN{background:var(--red)}.v-INCONCLUSIVE{background:var(--gray)}
.meta{display:flex;flex-wrap:wrap;gap:1.25rem;padding:1rem 2rem;border-bottom:1px solid var(--line)}
.meta-item span{display:block;color:var(--muted);font-size:.72rem;text-transform:uppercase;letter-spacing:.04em}
.meta-item b{font-size:.95rem}
.coverage{padding:.6rem 2rem;border-bottom:1px solid var(--line);font-size:.82rem;color:var(--muted)}
.coverage b{color:var(--fg)}
section{padding:1.25rem 2rem}h2{font-size:1.1rem;margin:.5rem 0 1rem}h4{margin:.75rem 0 .35rem;font-size:.82rem;color:var(--muted);text-transform:uppercase;letter-spacing:.03em}
table.pages{width:100%;border-collapse:collapse;font-size:.9rem}
.pages th{text-align:left;color:var(--muted);font-weight:600;font-size:.72rem;text-transform:uppercase;padding:.4rem .6rem;border-bottom:1px solid var(--line)}
.pages td{padding:.45rem .6rem;border-bottom:1px solid var(--line);vertical-align:top}
.pages .url{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.pages .src{color:var(--muted);font-size:.8rem}
a{color:inherit}
.pill{display:inline-block;padding:.1rem .45rem;border-radius:4px;font-size:.7rem;font-weight:700;color:#fff;white-space:nowrap}
.p-fail{background:var(--red)}.p-warn{background:var(--yellow)}.p-pass{background:var(--green)}.p-skipped{background:var(--gray)}
.detail{border:1px solid var(--line);border-radius:8px;margin:.6rem 0;background:var(--card)}
.detail summary{cursor:pointer;padding:.7rem 1rem;font-size:.9rem;list-style:none}
.detail summary::-webkit-details-marker{display:none}
.detail-body{padding:0 1rem 1rem}
.shots{display:flex;flex-wrap:wrap;gap:1rem;margin:.5rem 0}
figure{margin:0;max-width:520px}figure img{width:100%;border:1px solid var(--line);border-radius:6px;display:block}
figcaption{color:var(--muted);font-size:.75rem;margin-top:.25rem}
.evi ul{margin:.25rem 0;padding-left:1.1rem}.evi li{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.82rem;word-break:break-all}
.tag{background:var(--line);color:var(--muted);padding:0 .3rem;border-radius:3px;font-size:.7rem}
.note{color:var(--yellow);font-weight:600}
footer{padding:1.5rem 2rem;color:var(--muted);font-size:.8rem}
`;
